addSbtPlugin("com.dwijnand" % "sbt-dynver" % "4.1.1")
addSbtPlugin("org.scalameta" % "sbt-mdoc" % "2.3.7")
addSbtPlugin("org.scalameta" % "sbt-scalafmt" % "2.5.0")
addSbtPlugin("com.github.sbt" % "sbt-pgp" % "2.2.1")
addSbtPlugin("africa.shuwari.sbt" % "sbt-shuwari" % "0.9.6")
addSbtPlugin("org.xerial.sbt" % "sbt-sonatype" % "3.9.21")
